# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'coveralls/gcov/version'

Gem::Specification.new do |spec|
  spec.name          = "coveralls-gcov"
  spec.version       = Coveralls::Gcov::VERSION
  spec.authors       = ["kishikawa katsumi"]
  spec.email         = ["kishikawakatsumi@mac.com"]

  spec.summary       = %q{Upload coverage information generated by Gcov to coveralls.io.}
  spec.description   = %q{Upload coverage information generated by Gcov to coveralls.io.}
  spec.homepage      = "https://github.com/kishikawakatsumi/coveralls-gcov"
  spec.license       = "MIT"

  spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  spec.add_dependency "commander"

  spec.add_development_dependency "bundler", "~> 1.9"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "rspec"
end
